# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Ooi | Digital Architect, Full-Stack Developer & UI/UX
email: wengteikooi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  James Ooi is a digital architect, full-stack developer and UI/UX designer
  based in Kuala Lumpur that enjoys solving practical problems with innovative,
  usable and aesthetically pleasing solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jamesooi.design" # the base hostname & protocol for your site
twitter_username: jamesssooi
github_username:  jamesssooi

# Collections
collections:
  works:
    output: true
    permalink: /works/:title
    values:
      layout: work

# Defaults
defaults:
  - scope:
      path: ""
      type: works
    values:
      layout: work

# Build settings
markdown: kramdown

# Plugins
plugins:
- jekyll-autoprefixer
